apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiQmFrYW1paSIsInBhc3N3b3JkIjoiZ2hwX0RWekdibUJXYzZQRjByemFzbmJaRnEwS0JvZDdlejNKS0pvWSIsImF1dGgiOiJRbUZyWVcxcGFUcG5hSEJmUkZaNlIySnRRbGRqTmxCR01ISjZZWE51WWxwR2NUQkxRbTlrTjJWNk0wcExTbTlaIn19fQ==
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
